module: SwiftBeanCountCompassCardMapper
readme: README.md
clean: true
disable_search: true
author: Nef10
author_url: https://github.com/Nef10
root_url: https://Nef10.github.io/SwiftBeanCountCompassCardMapper/
github_url: https://github.com/Nef10/SwiftBeanCountCompassCardMapper
github_file_prefix: https://github.com/Nef10/SwiftBeanCountCompassCardMapper/blob/main
output: ./docs
theme: fullwidth
